api_version = "2025-04"

[[extensions]]
uid = "cart-line-remove-12345678-1234-1234-1234-123456789abc"
type = "ui_extension"
name = "checkout-line-remove"
handle = "checkout-line-remove"

[extensions.capabilities]
api_access = true

[[extensions.targeting]]
module = "./src/CartLineRemove.jsx"
target = "purchase.checkout.cart-line-item.render-after"
